package com.ridelink.payment.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import io.swagger.v3.oas.annotations.media.Schema;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * @author Paboda Diwyanjalee (IT24104072)
 *
 * A payment record persisted in the MongoDB payments collection.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "payments")
public class Payment {
    // 1. Database identifier for this payment record.
    @Id
    private String id;

    // 2. Link the payment to the ride and passenger it belongs to.
    private String rideId;
    private String passengerId;

    // 3. Store the charged amount and the method selected for payment.
    private Double amount;
    private PaymentMethod paymentMethod;

    // 4. The service sets the payment outcome and can change PENDING during processing.
    @Schema(description = "Payment result generated by the service", allowableValues = {"PENDING", "SUCCESS", "FAILED"}, accessMode = Schema.AccessMode.READ_ONLY)
    private PaymentStatus status;

    // 5. Record when the service created the payment.
    private LocalDateTime timestamp;
}